/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/users/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getUserById"];
    put: operations["updateUser"];
    post?: never;
    delete: operations["deleteUser"];
    options?: never;
    head?: never;
    patch: operations["patchUser"];
    trace?: never;
  };
  "/api/user-ecommerce/{EcommerceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["updateEcommerce"];
    post?: never;
    delete: operations["deleteEcommerce"];
    options?: never;
    head?: never;
    patch: operations["patchEcommerce"];
    trace?: never;
  };
  "/api/ecommerce/{EcommerceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["updateEcommerce_1"];
    post?: never;
    delete: operations["deleteEcommerce_1"];
    options?: never;
    head?: never;
    patch: operations["patchEcommerce_1"];
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["authenticate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index"];
    put?: never;
    post: operations["create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/{productId}/variations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_1"];
    put?: never;
    post: operations["create_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/{productId}/variations/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_2"];
    put?: never;
    post: operations["create_2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/tags/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_3"];
    put?: never;
    post: operations["create_3"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/categories/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_2"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/brands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_4"];
    put?: never;
    post: operations["create_4"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/brands/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_3"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_4"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_5"];
    put?: never;
    post: operations["create_5"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes/{attributeId}/terms": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_6"];
    put?: never;
    post: operations["create_6"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes/{attributeId}/terms/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_5"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_6"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_7"];
    put?: never;
    post: operations["create_7"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/coupons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["index_8"];
    put?: never;
    post: operations["create_8"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/coupons/batch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["batch_7"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAllUsers"];
    put?: never;
    post: operations["addNewUser"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-ecommerce": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAllEcommerces"];
    put?: never;
    post: operations["addNewEcommerce"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ecommerce": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAllEcommerces_1"];
    put?: never;
    post: operations["addNewEcommerce_1"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/{productId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show"];
    put?: never;
    post?: never;
    delete: operations["delete"];
    options?: never;
    head?: never;
    patch: operations["patch"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/{productId}/variations/{variationId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_1"];
    put?: never;
    post?: never;
    delete: operations["delete_1"];
    options?: never;
    head?: never;
    patch: operations["patch_1"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/tags/{tagId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_2"];
    put?: never;
    post?: never;
    delete: operations["delete_2"];
    options?: never;
    head?: never;
    patch: operations["patch_2"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/categories/{categoryId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_3"];
    put?: never;
    post?: never;
    delete: operations["delete_3"];
    options?: never;
    head?: never;
    patch: operations["patch_3"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/brands/{brandId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_4"];
    put?: never;
    post?: never;
    delete: operations["delete_4"];
    options?: never;
    head?: never;
    patch: operations["patch_4"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes/{attributeId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_5"];
    put?: never;
    post?: never;
    delete: operations["delete_5"];
    options?: never;
    head?: never;
    patch: operations["patch_5"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/products/attributes/{attributeId}/terms/{termId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_6"];
    put?: never;
    post?: never;
    delete: operations["delete_6"];
    options?: never;
    head?: never;
    patch: operations["patch_6"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/coupons/{couponId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_7"];
    put?: never;
    post?: never;
    delete: operations["delete_7"];
    options?: never;
    head?: never;
    patch: operations["patch_7"];
    trace?: never;
  };
  "/api/woocommerce/{ecommerceId}/media/{productId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["show_8"];
    put?: never;
    post?: never;
    delete: operations["delete_8"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/user-ecommerce/{ecommerceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getEcommerceById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ecommerce/{ecommerceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getEcommerceById_1"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateUserRequest: {
      name: string;
      roles: string;
      active: boolean;
    };
    ApiResponseUserResponse: {
      success?: boolean;
      data?: components["schemas"]["UserResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    UserResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      email?: string;
      roles?: string;
      active?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateOrUpdateUserEcommerceRequest: {
      /** Format: int32 */
      userId: number;
      /** Format: int32 */
      ecommerceId: number;
      apiPublic?: string;
      apiSecret?: string;
      appUsername?: string;
      appPassword?: string;
    };
    ApiResponseUserEcommerceResponse: {
      success?: boolean;
      data?: components["schemas"]["UserEcommerceResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    EcommerceResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      url?: string;
      /** @enum {string} */
      type?: "WORDPRESS";
      woocommerceApiVersion?: string;
      wordpressApiVersion?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    UserEcommerceResponse: {
      /** Format: int32 */
      id?: number;
      user?: components["schemas"]["UserResponse"];
      ecommerce?: components["schemas"]["EcommerceResponse"];
    };
    CreateOrUpdateEcommerceRequest: {
      name: string;
      url: string;
      /** @enum {string} */
      type: "WORDPRESS";
      woocommerceApiVersion?: string;
      wordpressApiVersion?: string;
    };
    ApiResponseEcommerceResponse: {
      success?: boolean;
      data?: components["schemas"]["EcommerceResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    UserRegisterRequest: {
      email: string;
      password: string;
      name: string;
    };
    ApiResponseUserLoginResponse: {
      success?: boolean;
      data?: components["schemas"]["UserLoginResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    UserLoginResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      email?: string;
      roles?: string;
      active?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      token?: string;
      /** Format: int64 */
      expiresIn?: number;
    };
    UserLoginRequest: {
      email: string;
      password: string;
    };
    DimensionsRequest: {
      length: string;
      width: string;
      height: string;
    };
    LinkToAttributeRequest: {
      /** Format: int32 */
      id?: number;
      name: string;
      /** Format: int32 */
      position?: number;
      visible?: boolean;
      variation?: boolean;
      options?: string[];
    };
    LinkToDefaultAttributeRequest: {
      /** Format: int32 */
      id?: number;
      name: string;
      option: string;
    };
    LinkToEntityUsingIdRequest: {
      /** Format: int32 */
      id: number;
    };
    WooCommerceDownloadRequest: {
      /** Format: int32 */
      id?: number;
      name: string;
      file: string;
    };
    WooCommerceMetaRequest: {
      /** Format: int32 */
      id?: number;
      key: string;
      value: string;
    };
    WooCommerceProductRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      link?: string;
      description?: string;
      shortDescription?: string;
      sku?: string;
      price?: string;
      slug?: string;
      permalink?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      type?: string;
      status?: string;
      featured?: boolean;
      catalogVisibility?: string;
      regularPrice?: string;
      salePrice?: string;
      dateOnSaleFrom?: string;
      dateOnSaleFromGmt?: string;
      dateOnSaleTo?: string;
      dateOnSaleToGmt?: string;
      virtual?: boolean;
      downloadable?: boolean;
      downloads?: components["schemas"]["WooCommerceDownloadRequest"][];
      /** Format: int32 */
      downloadLimit?: number;
      /** Format: int32 */
      downloadExpiry?: number;
      externalUrl?: string;
      buttonText?: string;
      taxStatus?: string;
      taxClass?: string;
      manageStock?: boolean;
      /** Format: int32 */
      stockQuantity?: number;
      stockStatus?: string;
      backorders?: string;
      soldIndividually?: boolean;
      weight?: string;
      dimensions?: components["schemas"]["DimensionsRequest"];
      shippingClass?: string;
      reviewsAllowed?: boolean;
      upsellIds?: number[];
      crossSellIds?: number[];
      /** Format: int32 */
      parentId?: number;
      purchaseNote?: string;
      categories?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      brands?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      tags?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      images?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      attributes?: components["schemas"]["LinkToAttributeRequest"][];
      defaultAttributes?: components["schemas"]["LinkToDefaultAttributeRequest"][];
      groupedProducts?: Record<string, never>[];
      /** Format: int32 */
      menuOrder?: number;
      metaData?: components["schemas"]["WooCommerceMetaRequest"][];
    };
    Ecommerce: {
      /** Format: int32 */
      id?: number;
      name?: string;
      url?: string;
      /** @enum {string} */
      type?: "WORDPRESS";
      woocommerceApiVersion?: string;
      wordpressApiVersion?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      userEcommerces?: components["schemas"]["UserEcommerce"][];
      users?: components["schemas"]["User"][];
    };
    GrantedAuthority: {
      authority?: string;
    };
    User: {
      /** Format: int32 */
      id?: number;
      name?: string;
      email?: string;
      roles?: string;
      active?: boolean;
      /** Format: date-time */
      lastLoginAt?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
      userEcommerces?: components["schemas"]["UserEcommerce"][];
      ecommerces?: components["schemas"]["Ecommerce"][];
      authorities?: components["schemas"]["GrantedAuthority"][];
      username?: string;
      enabled?: boolean;
      accountNonExpired?: boolean;
      accountNonLocked?: boolean;
      credentialsNonExpired?: boolean;
    };
    UserEcommerce: {
      /** Format: int32 */
      id?: number;
      user?: components["schemas"]["User"];
      ecommerce?: components["schemas"]["Ecommerce"];
      apiPublic?: string;
      apiSecret?: string;
      appUsername?: string;
      appPassword?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    ApiResponseWooCommerceProductResponse: {
      success?: boolean;
      data?: components["schemas"]["WooCommerceProductResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    DimensionsResponse: {
      length?: string;
      width?: string;
      height?: string;
    };
    LinkItem: {
      href?: string;
    };
    Links: {
      self?: components["schemas"]["LinkItem"][];
      collection?: components["schemas"]["LinkItem"][];
    };
    WooCommerceAttributeResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      /** Format: int32 */
      position?: number;
      visible?: boolean;
      variation?: boolean;
      options?: string[];
    };
    WooCommerceDefaultAttributeResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      option?: string;
    };
    WooCommerceDownloadResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      file?: string;
    };
    WooCommerceImage: {
      /** Format: int32 */
      id?: number;
      src?: string;
      name?: string;
      alt?: string;
      createdAt?: string;
      createdAtGmt?: string;
      updatedAt?: string;
      updatedAtGmt?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
    };
    WooCommerceMetaResponse: {
      /** Format: int32 */
      id?: number;
      key?: string;
      value?: string;
    };
    WooCommerceProductResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      link?: string;
      type?: string;
      status?: string;
      description?: string;
      sku?: string;
      price?: string;
      createdAt?: string;
      createdAtGmt?: string;
      updatedAt?: string;
      updatedAtGmt?: string;
      slug?: string;
      permalink?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      featured?: boolean;
      catalogVisibility?: string;
      shortDescription?: string;
      regularPrice?: string;
      salePrice?: string;
      dateOnSaleFrom?: string;
      dateOnSaleFromGmt?: string;
      dateOnSaleTo?: string;
      dateOnSaleToGmt?: string;
      priceHtml?: string;
      onSale?: boolean;
      purchasable?: boolean;
      /** Format: int32 */
      totalSales?: number;
      virtual?: boolean;
      downloadable?: boolean;
      downloads?: components["schemas"]["WooCommerceDownloadResponse"][];
      /** Format: int32 */
      downloadLimit?: number;
      /** Format: int32 */
      downloadExpiry?: number;
      externalUrl?: string;
      buttonText?: string;
      taxStatus?: string;
      taxClass?: string;
      manageStock?: boolean;
      /** Format: int32 */
      stockQuantity?: number;
      stockStatus?: string;
      backorders?: string;
      backordersAllowed?: boolean;
      backordered?: boolean;
      soldIndividually?: boolean;
      weight?: string;
      dimensions?: components["schemas"]["DimensionsResponse"];
      shippingRequired?: boolean;
      shippingTaxable?: boolean;
      shippingClass?: string;
      /** Format: int32 */
      shippingClassId?: number;
      reviewsAllowed?: boolean;
      averageRating?: string;
      /** Format: int32 */
      ratingCount?: number;
      relatedIds?: number[];
      upsellIds?: number[];
      crossSellIds?: number[];
      /** Format: int32 */
      parentId?: number;
      purchaseNote?: string;
      categories?: components["schemas"]["WoocommerceProductCategoryResponse"][];
      brands?: components["schemas"]["WoocommerceProductBrandResponse"][];
      tags?: components["schemas"]["WooCommerceTagResponse"][];
      images?: components["schemas"]["WooCommerceImage"][];
      defaultAttributes?: components["schemas"]["WooCommerceDefaultAttributeResponse"][];
      attributes?: components["schemas"]["WooCommerceAttributeResponse"][];
      variations?: number[];
      groupedProducts?: Record<string, never>[];
      /** Format: int32 */
      menuOrder?: number;
      metaData?: components["schemas"]["WooCommerceMetaResponse"][];
      get_links?: components["schemas"]["Links"];
    };
    WooCommerceTagResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
    };
    WoocommerceProductBrandResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      image?: components["schemas"]["WooCommerceImage"];
      /** Format: int32 */
      menuOrder?: number;
      /** Format: int32 */
      count?: number;
    };
    WoocommerceProductCategoryResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      display?: string;
      image?: components["schemas"]["WooCommerceImage"];
      /** Format: int32 */
      menuOrder?: number;
      /** Format: int32 */
      count?: number;
    };
    WooCommerceProductVariationRequest: {
      /** Format: int32 */
      id?: number;
      sku?: string;
      regularPrice?: string;
      salePrice?: string;
      dateOnSaleFrom?: string;
      dateOnSaleFromGmt?: string;
      dateOnSaleTo?: string;
      dateOnSaleToGmt?: string;
      status?: string;
      virtual?: boolean;
      downloadable?: boolean;
      downloads?: components["schemas"]["WooCommerceDownloadRequest"][];
      /** Format: int32 */
      downloadLimit?: number;
      /** Format: int32 */
      downloadExpiry?: number;
      taxStatus?: string;
      taxClass?: string;
      manageStock?: Record<string, never>;
      /** Format: int32 */
      stockQuantity?: number;
      stockStatus?: string;
      backorders?: string;
      weight?: string;
      dimensions?: components["schemas"]["DimensionsRequest"];
      shippingClass?: string;
      image?: components["schemas"]["LinkToEntityUsingIdRequest"];
      attributes?: components["schemas"]["LinkToDefaultAttributeRequest"][];
      /** Format: int32 */
      menuOrder?: number;
      metaData?: components["schemas"]["WooCommerceMetaRequest"][];
    };
    ApiResponseWooCommerceProductVariationResponse: {
      success?: boolean;
      data?: components["schemas"]["WooCommerceProductVariationResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    WooCommerceProductVariationResponse: {
      /** Format: int32 */
      id?: number;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      description?: string;
      permalink?: string;
      sku?: string;
      globalUniqueId?: string;
      price?: string;
      regularPrice?: string;
      salePrice?: string;
      dateOnSaleFrom?: string;
      dateOnSaleFromGmt?: string;
      dateOnSaleTo?: string;
      dateOnSaleToGmt?: string;
      onSale?: boolean;
      /** @enum {string} */
      status?: "draft" | "pending" | "private" | "publish";
      purchasable?: boolean;
      virtual?: boolean;
      downloadable?: boolean;
      downloads?: components["schemas"]["WooCommerceDownloadResponse"][];
      /** Format: int32 */
      downloadLimit?: number;
      /** Format: int32 */
      downloadExpiry?: number;
      /** @enum {string} */
      taxStatus?: "taxable" | "shipping" | "none";
      taxClass?: string;
      manageStock?: Record<string, never>;
      /** Format: int32 */
      stockQuantity?: number;
      /** @enum {string} */
      stockStatus?: "instock" | "outofstock" | "onbackorder";
      /** @enum {string} */
      backorders?: "no" | "notify" | "yes";
      backordersAllowed?: boolean;
      backordered?: boolean;
      weight?: string;
      dimensions?: components["schemas"]["DimensionsResponse"];
      shippingClass?: string;
      shippingClassId?: string;
      image?: components["schemas"]["WooCommerceImage"];
      attributes?: components["schemas"]["WooCommerceDefaultAttributeResponse"][];
      /** Format: int32 */
      menuOrder?: number;
      metaData?: components["schemas"]["WooCommerceMetaResponse"][];
      createdAt?: string;
      updatedAt?: string;
      link?: string;
      createdAtGmt?: string;
      updatedAtGmt?: string;
    };
    BatchWoocommerceProductVariationRequest: {
      create?: components["schemas"]["WooCommerceProductVariationRequest"][];
      update?: components["schemas"]["WooCommerceProductVariationRequest"][];
      delete?: number[];
    };
    ApiResponseBatchWooCommerceProductVariationResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWooCommerceProductVariationResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWooCommerceProductVariationResponse: {
      create?: components["schemas"]["WooCommerceProductVariationResponse"][];
      update?: components["schemas"]["WooCommerceProductVariationResponse"][];
      delete?: components["schemas"]["WooCommerceProductVariationResponse"][];
    };
    WooCommerceCreateProductTagRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
    };
    ApiResponseWoocommerceProductTagResponse: {
      success?: boolean;
      data?: components["schemas"]["WoocommerceProductTagResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    WoocommerceProductTagResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      /** Format: int32 */
      count?: number;
    };
    BatchWoocommerceProductTagRequest: {
      create?: components["schemas"]["WooCommerceCreateProductTagRequest"][];
      update?: components["schemas"]["WooCommerceProductTagRequest"][];
      delete?: number[];
    };
    WooCommerceProductTagRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
    };
    ApiResponseBatchWoocommerceProductTagResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceProductTagResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductTagResponse: {
      create?: components["schemas"]["WoocommerceProductTagResponse"][];
      update?: components["schemas"]["WoocommerceProductTagResponse"][];
      delete?: components["schemas"]["WoocommerceProductTagResponse"][];
    };
    WooCommerceCreateProductCategoryRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      display?: string;
      image?: components["schemas"]["LinkToEntityUsingIdRequest"];
      /** Format: int32 */
      menuOrder?: number;
    };
    ApiResponseWoocommerceProductCategoryResponse: {
      success?: boolean;
      data?: components["schemas"]["WoocommerceProductCategoryResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductCategoryRequest: {
      create?: components["schemas"]["WooCommerceCreateProductCategoryRequest"][];
      update?: components["schemas"]["WooCommerceProductCategoryRequest"][];
      delete?: number[];
    };
    WooCommerceProductCategoryRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      display?: string;
      image?: components["schemas"]["LinkToEntityUsingIdRequest"];
      /** Format: int32 */
      menuOrder?: number;
    };
    ApiResponseBatchWoocommerceProductCategoryResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceProductCategoryResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductCategoryResponse: {
      create?: components["schemas"]["WoocommerceProductCategoryResponse"][];
      update?: components["schemas"]["WoocommerceProductCategoryResponse"][];
      delete?: components["schemas"]["WoocommerceProductCategoryResponse"][];
    };
    WooCommerceCreateProductBrandRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      image?: components["schemas"]["LinkToEntityUsingIdRequest"];
      /** Format: int32 */
      menuOrder?: number;
    };
    ApiResponseWoocommerceProductBrandResponse: {
      success?: boolean;
      data?: components["schemas"]["WoocommerceProductBrandResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductBrandRequest: {
      create?: components["schemas"]["WooCommerceCreateProductBrandRequest"][];
      update?: components["schemas"]["WooCommerceProductBrandRequest"][];
      delete?: number[];
    };
    WooCommerceProductBrandRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      /** Format: int32 */
      parent?: number;
      description?: string;
      image?: components["schemas"]["LinkToEntityUsingIdRequest"];
      /** Format: int32 */
      menuOrder?: number;
    };
    ApiResponseBatchWoocommerceProductBrandResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceProductBrandResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductBrandResponse: {
      create?: components["schemas"]["WoocommerceProductBrandResponse"][];
      update?: components["schemas"]["WoocommerceProductBrandResponse"][];
      delete?: components["schemas"]["WoocommerceProductBrandResponse"][];
    };
    BatchWoocommerceProductRequest: {
      create?: components["schemas"]["WooCommerceProductRequest"][];
      update?: components["schemas"]["UpdateWoocommerceProductRequest"][];
      delete?: number[];
    };
    UpdateWoocommerceProductRequest: {
      /** Format: int32 */
      id: number;
      name?: string;
      link?: string;
      description?: string;
      shortDescription?: string;
      sku?: string;
      price?: string;
      slug?: string;
      permalink?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      type?: string;
      status?: string;
      featured?: boolean;
      catalogVisibility?: string;
      regularPrice?: string;
      salePrice?: string;
      dateOnSaleFrom?: string;
      dateOnSaleFromGmt?: string;
      dateOnSaleTo?: string;
      dateOnSaleToGmt?: string;
      virtual?: boolean;
      downloadable?: boolean;
      downloads?: components["schemas"]["WooCommerceDownloadRequest"][];
      /** Format: int32 */
      downloadLimit?: number;
      /** Format: int32 */
      downloadExpiry?: number;
      externalUrl?: string;
      buttonText?: string;
      taxStatus?: string;
      taxClass?: string;
      manageStock?: boolean;
      /** Format: int32 */
      stockQuantity?: number;
      stockStatus?: string;
      backorders?: string;
      soldIndividually?: boolean;
      weight?: string;
      dimensions?: components["schemas"]["DimensionsRequest"];
      shippingClass?: string;
      reviewsAllowed?: boolean;
      upsellIds?: number[];
      crossSellIds?: number[];
      /** Format: int32 */
      parentId?: number;
      purchaseNote?: string;
      categories?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      brands?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      tags?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      images?: components["schemas"]["LinkToEntityUsingIdRequest"][];
      attributes?: components["schemas"]["LinkToAttributeRequest"][];
      defaultAttributes?: components["schemas"]["LinkToDefaultAttributeRequest"][];
      groupedProducts?: Record<string, never>[];
      /** Format: int32 */
      menuOrder?: number;
      metaData?: components["schemas"]["WooCommerceMetaRequest"][];
    };
    ApiResponseBatchWoocommerceProductResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceProductResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductResponse: {
      create?: components["schemas"]["WooCommerceProductResponse"][];
      update?: components["schemas"]["WooCommerceProductResponse"][];
      delete?: components["schemas"]["WooCommerceProductResponse"][];
    };
    WooCommerceCreateProductAttributeRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      orderBy?: string;
      hasArchives?: boolean;
    };
    ApiResponseWooCommerceProductAttributeResponse: {
      success?: boolean;
      data?: components["schemas"]["WooCommerceProductAttributeResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    WooCommerceProductAttributeResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      type?: string;
      orderBy?: string;
      hasArchives?: boolean;
    };
    WoocommerceCreateProductAttributeTermRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      /** Format: int32 */
      menuOrder?: number;
      nameValid?: boolean;
    };
    ApiResponseWoocommerceProductAttributeTermResponse: {
      success?: boolean;
      data?: components["schemas"]["WoocommerceProductAttributeTermResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    WoocommerceProductAttributeTermResponse: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      /** Format: int32 */
      menuOrder?: number;
      /** Format: int32 */
      count?: number;
    };
    BatchWoocommerceProductAttributeTermRequest: {
      create?: components["schemas"]["WoocommerceCreateProductAttributeTermRequest"][];
      update?: components["schemas"]["WoocommerceProductAttributeTermRequest"][];
      delete?: number[];
    };
    WoocommerceProductAttributeTermRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      description?: string;
      /** Format: int32 */
      menuOrder?: number;
    };
    ApiResponseBatchWoocommerceProductAttributeTermResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceProductAttributeTermResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceProductAttributeTermResponse: {
      create?: components["schemas"]["WoocommerceProductAttributeTermResponse"][];
      update?: components["schemas"]["WoocommerceProductAttributeTermResponse"][];
      delete?: components["schemas"]["WoocommerceProductAttributeTermResponse"][];
    };
    BatchWoocommerceProductAttributeRequest: {
      create?: components["schemas"]["WooCommerceCreateProductAttributeRequest"][];
      update?: components["schemas"]["WooCommerceProductAttributeRequest"][];
      delete?: number[];
    };
    WooCommerceProductAttributeRequest: {
      /** Format: int32 */
      id?: number;
      name?: string;
      slug?: string;
      orderBy?: string;
      hasArchives?: boolean;
    };
    ApiResponseBatchWooCommerceProductAttributeResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWooCommerceProductAttributeResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWooCommerceProductAttributeResponse: {
      create?: components["schemas"]["WooCommerceProductAttributeResponse"][];
      update?: components["schemas"]["WooCommerceProductAttributeResponse"][];
      delete?: components["schemas"]["WooCommerceProductAttributeResponse"][];
    };
    CreateWordpressMediaRequest: {
      title?: string;
      caption?: string;
      description?: string;
      altText?: string;
      /** Format: int32 */
      post?: number;
      status?: string;
    };
    ApiResponseWordpressMediaResponse: {
      success?: boolean;
      data?: components["schemas"]["WordpressMediaResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    Rendered: {
      rendered?: string;
      get_protected?: boolean;
    };
    WordpressMediaResponse: {
      /** Format: int32 */
      id?: number;
      date?: string;
      dateGmt?: string;
      modified?: string;
      modifiedGmt?: string;
      guid?: components["schemas"]["Rendered"];
      title?: components["schemas"]["Rendered"];
      caption?: components["schemas"]["Rendered"];
      description?: components["schemas"]["Rendered"];
      link?: string;
      slug?: string;
      status?: string;
      type?: string;
      permalinkTemplate?: string;
      generatedSlug?: string;
      /** Format: int32 */
      author?: number;
      commentStatus?: string;
      pingStatus?: string;
      template?: string;
      altText?: string;
      mediaType?: string;
      mimeType?: string;
      mediaDetails?: {
        [key: string]: Record<string, never>;
      };
      /** Format: int32 */
      post?: number;
      sourceUrl?: string;
      missingImageSizes?: string[];
      createdAt?: string;
      updatedAt?: string;
      createdAtGmt?: string;
      updatedAtGmt?: string;
    };
    WoocommerceCreateCouponRequest: {
      /** Format: int32 */
      id?: number;
      code?: string;
      amount?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      /** @enum {string} */
      discountType?: "percent" | "fixed_cart" | "fixed_product";
      description?: string;
      dateExpires?: string;
      dateExpiresGmt?: string;
      /** Format: int32 */
      usageCount?: number;
      individualUse?: boolean;
      productIds?: number[];
      excludedProductIds?: number[];
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usageLimitPerUser?: number;
      /** Format: int32 */
      limitUsageToXItems?: number;
      freeShipping?: boolean;
      productCategories?: number[];
      excludedProductCategories?: number[];
      excludeSaleItems?: boolean;
      minimumAmount?: string;
      maximumAmount?: string;
      emailRestrictions?: string[];
      usedBy?: string[];
      metaData?: components["schemas"]["WooCommerceMetaRequest"][];
    };
    ApiResponseWoocommerceCouponResponse: {
      success?: boolean;
      data?: components["schemas"]["WoocommerceCouponResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    WoocommerceCouponResponse: {
      /** Format: int32 */
      id?: number;
      code?: string;
      amount?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      /** @enum {string} */
      discountType?: "percent" | "fixed_cart" | "fixed_product";
      description?: string;
      dateExpires?: string;
      dateExpiresGmt?: string;
      /** Format: int32 */
      usageCount?: number;
      individualUse?: boolean;
      productIds?: number[];
      excludedProductIds?: number[];
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usageLimitPerUser?: number;
      /** Format: int32 */
      limitUsageToXItems?: number;
      freeShipping?: boolean;
      productCategories?: number[];
      excludedProductCategories?: number[];
      excludeSaleItems?: boolean;
      minimumAmount?: string;
      maximumAmount?: string;
      emailRestrictions?: string[];
      usedBy?: string[];
      metaData?: components["schemas"]["WooCommerceMetaResponse"][];
      createdAt?: string;
      updatedAt?: string;
      createdAtGmt?: string;
      updatedAtGmt?: string;
    };
    BatchWoocommerceCouponRequest: {
      create?: components["schemas"]["WoocommerceCreateCouponRequest"][];
      update?: components["schemas"]["WoocommerceCouponRequest"][];
      delete?: number[];
    };
    WoocommerceCouponRequest: {
      /** Format: int32 */
      id?: number;
      code?: string;
      amount?: string;
      dateCreated?: string;
      dateCreatedGmt?: string;
      dateModified?: string;
      dateModifiedGmt?: string;
      /** @enum {string} */
      discountType?: "percent" | "fixed_cart" | "fixed_product";
      description?: string;
      dateExpires?: string;
      dateExpiresGmt?: string;
      /** Format: int32 */
      usageCount?: number;
      individualUse?: boolean;
      productIds?: number[];
      excludedProductIds?: number[];
      /** Format: int32 */
      usageLimit?: number;
      /** Format: int32 */
      usageLimitPerUser?: number;
      /** Format: int32 */
      limitUsageToXItems?: number;
      freeShipping?: boolean;
      productCategories?: number[];
      excludedProductCategories?: number[];
      excludeSaleItems?: boolean;
      minimumAmount?: string;
      maximumAmount?: string;
      emailRestrictions?: string[];
      usedBy?: string[];
      metaData?: components["schemas"]["WooCommerceMetaRequest"][];
    };
    ApiResponseBatchWoocommerceCouponResponse: {
      success?: boolean;
      data?: components["schemas"]["BatchWoocommerceCouponResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    BatchWoocommerceCouponResponse: {
      create?: components["schemas"]["WoocommerceCouponResponse"][];
      update?: components["schemas"]["WoocommerceCouponResponse"][];
      delete?: components["schemas"]["WoocommerceCouponResponse"][];
    };
    CreateUserRequest: {
      name: string;
      roles: string;
      active: boolean;
      email: string;
      password: string;
    };
    PatchUserRequest: {
      name?: string;
      roles?: string;
      active?: boolean;
    };
    PatchUserEcommerceRequest: {
      /** Format: int32 */
      userId?: number;
      /** Format: int32 */
      ecommerceId?: number;
      apiPublic?: string;
      apiSecret?: string;
      appUsername?: string;
      appPassword?: string;
    };
    PatchEcommerceRequest: {
      name?: string;
      url?: string;
      /** @enum {string} */
      type?: "WORDPRESS";
      woocommerceApiVersion?: string;
      wordpressApiVersion?: string;
    };
    IndexRequest: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      perPage?: number;
      fields?: string;
      search?: string;
      searchFields?: string[];
    };
    ApiResponsePageWooCommerceProductResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWooCommerceProductResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWooCommerceProductResponse: {
      items?: components["schemas"]["WooCommerceProductResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWooCommerceProductVariationResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWooCommerceProductVariationResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWooCommerceProductVariationResponse: {
      items?: components["schemas"]["WooCommerceProductVariationResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWoocommerceProductTagResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWoocommerceProductTagResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWoocommerceProductTagResponse: {
      items?: components["schemas"]["WoocommerceProductTagResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWoocommerceProductCategoryResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWoocommerceProductCategoryResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWoocommerceProductCategoryResponse: {
      items?: components["schemas"]["WoocommerceProductCategoryResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWoocommerceProductBrandResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWoocommerceProductBrandResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWoocommerceProductBrandResponse: {
      items?: components["schemas"]["WoocommerceProductBrandResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWooCommerceProductAttributeResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWooCommerceProductAttributeResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWooCommerceProductAttributeResponse: {
      items?: components["schemas"]["WooCommerceProductAttributeResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWoocommerceProductAttributeTermResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWoocommerceProductAttributeTermResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWoocommerceProductAttributeTermResponse: {
      items?: components["schemas"]["WoocommerceProductAttributeTermResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWordpressMediaResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWordpressMediaResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWordpressMediaResponse: {
      items?: components["schemas"]["WordpressMediaResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponsePageWoocommerceCouponResponse: {
      success?: boolean;
      data?: components["schemas"]["PageWoocommerceCouponResponse"];
      message?: string;
      errors?: Record<string, never>;
    };
    PageWoocommerceCouponResponse: {
      items?: components["schemas"]["WoocommerceCouponResponse"][];
      /** Format: int32 */
      currentPage?: number;
      /** Format: int32 */
      itemsInPage?: number;
      /** Format: int32 */
      totalItems?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    ApiResponseListUserResponse: {
      success?: boolean;
      data?: components["schemas"]["UserResponse"][];
      message?: string;
      errors?: Record<string, never>;
    };
    ApiResponseListUserEcommerceResponse: {
      success?: boolean;
      data?: components["schemas"]["UserEcommerceResponse"][];
      message?: string;
      errors?: Record<string, never>;
    };
    ApiResponseListEcommerceResponse: {
      success?: boolean;
      data?: components["schemas"]["EcommerceResponse"][];
      message?: string;
      errors?: Record<string, never>;
    };
    DeleteRequest: {
      force?: boolean;
    };
    ApiResponseBoolean: {
      success?: boolean;
      data?: boolean;
      message?: string;
      errors?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseUserResponse"];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserResponse"];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patchUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchUserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserResponse"];
        };
      };
    };
  };
  updateEcommerce: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateUserEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserEcommerceResponse"];
        };
      };
    };
  };
  deleteEcommerce: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patchEcommerce: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchUserEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserEcommerceResponse"];
        };
      };
    };
  };
  updateEcommerce_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseEcommerceResponse"];
        };
      };
    };
  };
  deleteEcommerce_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patchEcommerce_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        EcommerceId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PatchEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseEcommerceResponse"];
        };
      };
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegisterRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserLoginResponse"];
        };
      };
    };
  };
  authenticate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserLoginResponse"];
        };
      };
    };
  };
  index: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWooCommerceProductResponse"];
        };
      };
    };
  };
  create: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductResponse"];
        };
      };
    };
  };
  index_1: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWooCommerceProductVariationResponse"];
        };
      };
    };
  };
  create_1: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductVariationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductVariationResponse"];
        };
      };
    };
  };
  batch: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductVariationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWooCommerceProductVariationResponse"];
        };
      };
    };
  };
  index_2: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWoocommerceProductTagResponse"];
        };
      };
    };
  };
  create_2: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceCreateProductTagRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductTagResponse"];
        };
      };
    };
  };
  batch_1: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductTagRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceProductTagResponse"];
        };
      };
    };
  };
  index_3: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWoocommerceProductCategoryResponse"];
        };
      };
    };
  };
  create_3: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceCreateProductCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductCategoryResponse"];
        };
      };
    };
  };
  batch_2: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceProductCategoryResponse"];
        };
      };
    };
  };
  index_4: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWoocommerceProductBrandResponse"];
        };
      };
    };
  };
  create_4: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceCreateProductBrandRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductBrandResponse"];
        };
      };
    };
  };
  batch_3: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductBrandRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceProductBrandResponse"];
        };
      };
    };
  };
  batch_4: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceProductResponse"];
        };
      };
    };
  };
  index_5: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWooCommerceProductAttributeResponse"];
        };
      };
    };
  };
  create_5: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceCreateProductAttributeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductAttributeResponse"];
        };
      };
    };
  };
  index_6: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWoocommerceProductAttributeTermResponse"];
        };
      };
    };
  };
  create_6: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WoocommerceCreateProductAttributeTermRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductAttributeTermResponse"];
        };
      };
    };
  };
  batch_5: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductAttributeTermRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceProductAttributeTermResponse"];
        };
      };
    };
  };
  batch_6: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceProductAttributeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWooCommerceProductAttributeResponse"];
        };
      };
    };
  };
  index_7: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWordpressMediaResponse"];
        };
      };
    };
  };
  create_7: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          request?: components["schemas"]["CreateWordpressMediaRequest"];
          userEcommerce?: components["schemas"]["UserEcommerce"];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWordpressMediaResponse"];
        };
      };
    };
  };
  index_8: {
    parameters: {
      query: {
        request: components["schemas"]["IndexRequest"];
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponsePageWoocommerceCouponResponse"];
        };
      };
    };
  };
  create_8: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WoocommerceCreateCouponRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceCouponResponse"];
        };
      };
    };
  };
  batch_7: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BatchWoocommerceCouponRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBatchWoocommerceCouponResponse"];
        };
      };
    };
  };
  getAllUsers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseListUserResponse"];
        };
      };
    };
  };
  addNewUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserResponse"];
        };
      };
    };
  };
  getAllEcommerces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseListUserEcommerceResponse"];
        };
      };
    };
  };
  addNewEcommerce: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateUserEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseUserEcommerceResponse"];
        };
      };
    };
  };
  getAllEcommerces_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseListEcommerceResponse"];
        };
      };
    };
  };
  addNewEcommerce_1: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrUpdateEcommerceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ApiResponseEcommerceResponse"];
        };
      };
    };
  };
  show: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductResponse"];
        };
      };
    };
  };
  delete: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductResponse"];
        };
      };
    };
  };
  show_1: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
        variationId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductVariationResponse"];
        };
      };
    };
  };
  delete_1: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
        variationId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_1: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
        variationId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductVariationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductVariationResponse"];
        };
      };
    };
  };
  show_2: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        tagId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductTagResponse"];
        };
      };
    };
  };
  delete_2: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        tagId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_2: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        tagId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductTagRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductTagResponse"];
        };
      };
    };
  };
  show_3: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductCategoryResponse"];
        };
      };
    };
  };
  delete_3: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_3: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        categoryId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductCategoryRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductCategoryResponse"];
        };
      };
    };
  };
  show_4: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        brandId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductBrandResponse"];
        };
      };
    };
  };
  delete_4: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        brandId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_4: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        brandId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductBrandRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductBrandResponse"];
        };
      };
    };
  };
  show_5: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductAttributeResponse"];
        };
      };
    };
  };
  delete_5: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_5: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WooCommerceProductAttributeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWooCommerceProductAttributeResponse"];
        };
      };
    };
  };
  show_6: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
        termId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductAttributeTermResponse"];
        };
      };
    };
  };
  delete_6: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
        termId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_6: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        attributeId: number;
        termId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WoocommerceProductAttributeTermRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceProductAttributeTermResponse"];
        };
      };
    };
  };
  show_7: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        couponId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceCouponResponse"];
        };
      };
    };
  };
  delete_7: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        couponId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  patch_7: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        couponId: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WoocommerceCouponRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWoocommerceCouponResponse"];
        };
      };
    };
  };
  show_8: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseWordpressMediaResponse"];
        };
      };
    };
  };
  delete_8: {
    parameters: {
      query: {
        userEcommerce: components["schemas"]["UserEcommerce"];
      };
      header?: never;
      path: {
        productId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseBoolean"];
        };
      };
    };
  };
  getEcommerceById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ecommerceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseUserEcommerceResponse"];
        };
      };
    };
  };
  getEcommerceById_1: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        ecommerceId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApiResponseEcommerceResponse"];
        };
      };
    };
  };
}
